<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class CurriculumSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('curriculums')->insert([

            [ //小学1年生オフ
              'id' => null,
              'title' => '授業1',
              'thumbnail' => null,
              'description' => '授業1 小学1年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 1,
            ],
            [
              'id' => null,
              'title' => '授業2',
              'thumbnail' => null,
              'description' => '授業2 小学1年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 1,
            ],
            [
              'id' => null,
              'title' => '授業3',
              'thumbnail' => null,
              'description' => '授業3 小学1年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 1,
            ],
            [// 小学1年生オン
              'id' => null,
              'title' => '授業4',
              'thumbnail' => null,
              'description' => '授業4 小学1年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 1,
            ],
            [
                'id' => null,
                'title' => '授業5',
                'thumbnail' => null,
                'description' => '授業5 小学1年生 常時配信オン',
                'video_url' => null,
                'always_delivery_flg' => 1,
                'grade_id' => 1,
            ],
            [
                'id' => null,
                'title' => '授業6',
                'thumbnail' => null,
                'description' => '授業6 小学1年生 常時配信オン',
                'video_url' => null,
                'always_delivery_flg' => 1,
                'grade_id' => 1,
            ],
            [// 小学2年生オフ
              'id' => null,
              'title' => '授業7',
              'thumbnail' => null,
              'description' => '授業7 小学2年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 2,
            ],
            [
                'id' => null,
                'title' => '授業8',
                'thumbnail' => null,
                'description' => '授業8 小学2年生 常時配信オフ',
                'video_url' => null,
                'always_delivery_flg' => 0,
                'grade_id' => 2,
            ],
            [
                'id' => null,
                'title' => '授業9',
                'thumbnail' => null,
                'description' => '授業9 小学2年生 常時配信オフ',
                'video_url' => null,
                'always_delivery_flg' => 0,
                'grade_id' => 2,
              ],
            [ //小学2年生オン
                'id' => null,
                'title' => '授業10',
                'thumbnail' => null,
                'description' => '授業10 小学2年生 常時配信オン',
                'video_url' => null,
                'always_delivery_flg' => 1,
                'grade_id' => 2,
            ],
            [
                'id' => null,
                'title' => '授業11',
                'thumbnail' => null,
                'description' => '授業11 小学2年生 常時配信オン',
                'video_url' => null,
                'always_delivery_flg' => 1,
                'grade_id' => 2,
            ],
            [
                'id' => null,
                'title' => '授業12',
                'thumbnail' => null,
                'description' => '授業12 小学2年生 常時配信オン',
                'video_url' => null,
                'always_delivery_flg' => 1,
                'grade_id' => 2,
            ],
            [ // 3年生オフ
              'id' => null,
              'title' => '授業13',
              'thumbnail' => null,
              'description' => '授業13 小学3年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 3,
            ],
            [
              'id' => null,
              'title' => '授業14',
              'thumbnail' => null,
              'description' => '授業14 小学3年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 3,
            ],
            [
              'id' => null,
              'title' => '授業15',
              'thumbnail' => null,
              'description' => '授業15 小学3年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 3,
            ],
            [ //小学3年生オン
              'id' => null,
              'title' => '授業16',
              'thumbnail' => null,
              'description' => '授業16 小学3年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 3,
            ],
            [
              'id' => null,
              'title' => '授業17',
              'thumbnail' => null,
              'description' => '授業17 小学3年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 3,
            ],
            [
              'id' => null,
              'title' => '授業18',
              'thumbnail' => null,
              'description' => '授業18 小学3年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 3,
            ],
            [// 小学4年生オフ
              'id' => null,
              'title' => '授業20',
              'thumbnail' => null,
              'description' => '授業20 小学4年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 4,
            ],
            [
              'id' => null,
              'title' => '授業21',
              'thumbnail' => null,
              'description' => '授業21 小学4年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 4,
            ],
            [
              'id' => null,
              'title' => '授業22',
              'thumbnail' => null,
              'description' => '授業22 小学4年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 4,
            ],
            [//小学4年生オン
              'id' => null,
              'title' => '授業23',
              'thumbnail' => null,
              'description' => '授業23 小学4年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 4,
            ],
            [
              'id' => null,
              'title' => '授業24',
              'thumbnail' => null,
              'description' => '授業24 小学4年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 4,
            ],
            [
              'id' => null,
              'title' => '授業25',
              'thumbnail' => null,
              'description' => '授業25 小学4年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 4,
            ],
            [// 小学5年生オフ
              'id' => null,
              'title' => '授業26',
              'thumbnail' => null,
              'description' => '授業26 小学5年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 5,
            ],
            [
              'id' => null,
              'title' => '授業27',
              'thumbnail' => null,
              'description' => '授業27 小学5年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 5,
            ],
            [
              'id' => null,
              'title' => '授業28',
              'thumbnail' => null,
              'description' => '授業28 小学5年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 5,
            ],
            [//小学5年生オン
              'id' => null,
              'title' => '授業29',
              'thumbnail' => null,
              'description' => '授業29 小学5年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 5,
            ],
            [
              'id' => null,
              'title' => '授業30',
              'thumbnail' => null,
              'description' => '授業30 小学5年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 5,
            ],
            [
              'id' => null,
              'title' => '授業31',
              'thumbnail' => null,
              'description' => '授業31 小学5年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 5,
            ],
            [//小学6年生オフ
              'id' => null,
              'title' => '授業32',
              'thumbnail' => null,
              'description' => '授業32 小学6年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 6,
            ],
            [
              'id' => null,
              'title' => '授業33',
              'thumbnail' => null,
              'description' => '授業33 小学6年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 6,
            ],
            [
              'id' => null,
              'title' => '授業34',
              'thumbnail' => null,
              'description' => '授業34 小学6年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 6,
            ],
            [// 小学6年生オン
              'id' => null,
              'title' => '授業35',
              'thumbnail' => null,
              'description' => '授業35 小学6年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 6,
            ],
            [
              'id' => null,
              'title' => '授業36',
              'thumbnail' => null,
              'description' => '授業36 小学6年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 6,
            ],
            [
              'id' => null,
              'title' => '授業37',
              'thumbnail' => null,
              'description' => '授業37 小学6年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 6,
            ],
            [ //中学1年生オフ
              'id' => null,
              'title' => '授業38',
              'thumbnail' => null,
              'description' => '授業38 中学1年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 7,
            ],
            [ //中学1年生オン
              'id' => null,
              'title' => '授業39',
              'thumbnail' => null,
              'description' => '授業39 中学1年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 7,
            ],
            [ //中学2年生オフ
              'id' => null,
              'title' => '授業40',
              'thumbnail' => null,
              'description' => '授業40 中学2年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 8,
            ],
            [ //中学2年生オン
              'id' => null,
              'title' => '授業41',
              'thumbnail' => null,
              'description' => '授業41 中学2年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 8,
            ],
            [ //中学3年生オフ
              'id' => null,
              'title' => '授業42',
              'thumbnail' => null,
              'description' => '授業42 中学3年生 常時配信オフ',
              'video_url' => null,
              'always_delivery_flg' => 0,
              'grade_id' => 9,
            ],
            [ //中学3年生オン
              'id' => null,
              'title' => '授業43',
              'thumbnail' => null,
              'description' => '授業43 中学3年生 常時配信オン',
              'video_url' => null,
              'always_delivery_flg' => 1,
              'grade_id' => 9,
            ],
              [ //高校1年生オフ
                'id' => null,
                'title' => '授業44',
                'thumbnail' => null,
                'description' => '授業44 高校1年生 常時配信オフ',
                'video_url' => null,
                'always_delivery_flg' => 0,
                'grade_id' => 10,
              ],
              [ //高校1年生オフ
                'id' => null,
                'title' => '授業45',
                'thumbnail' => null,
                'description' => '授業45 高校1年生 常時配信オン',
                'video_url' => null,
                'always_delivery_flg' => 1,
                'grade_id' => 10,
              ],
              [ //高校2年生オフ
                'id' => null,
                'title' => '授業46',
                'thumbnail' => null,
                'description' => '授業46 高校2年生 常時配信オフ',
                'video_url' => null,
                'always_delivery_flg' => 0,
                'grade_id' => 11,
              ],
              [ //高校2年生オン
                'id' => null,
                'title' => '授業47',
                'thumbnail' => null,
                'description' => '授業47 高校2年生 常時配信オン',
                'video_url' => null,
                'always_delivery_flg' => 1,
                'grade_id' => 11,
              ],
              [ //高校3年生オフ
                'id' => null,
                'title' => '授業48',
                'thumbnail' => null,
                'description' => '授業48 高校3年生 常時配信オフ',
                'video_url' => null,
                'always_delivery_flg' => 0,
                'grade_id' => 12,
              ],
              [ //高校3年生オン
                'id' => null,
                'title' => '授業49',
                'thumbnail' => null,
                'description' => '授業49 高校3年生 常時配信オン',
                'video_url' => null,
                'always_delivery_flg' => 1,
                'grade_id' => 12,
              ]
            
            
            
          ]);
    }
}
